
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        # build-time value for Vite (fallback in code is http://localhost:8000)
        VITE_API_BASE: "http://localhost:8000"
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
